[project]
name = "baedal-control"
version = "0.1.0"
description = "RPA-integrated delivery app management console simulator"
requires-python = ">=3.11"
dependencies = []

[tool.pytest.ini_options]
testpaths = ["src/tests"]
pythonpath = ["src"]
